### ISSUE TITLE
Support more networks

### ISSUE THREAD

**Issue by matbour** [pugson/abi-data#3]
AFAIK after reading the source code, I found that the app only supports Ethereum Mainnet and Goerli testnet. Since the most used networks also have their etherscan-like explorers, like Polygon has polygonscan.com, etc. It should be possible to include the support for all of these.

I will be very happy to submit a PR if maintainers are interested.

**Comment by pugson** [comment]
Sure, go for it!

**Comment by matbour** [comment]
Done in #4
